services:
  pg:
    image: postgres:16.0-alpine3.18
    container_name: mochilando-dev
    # environment:
    #   # POSTGRES_USER: "local_user"
    #   # POSTGRES_PASSWORD: "local_password"
    #   POSTGRES_DB: "reposhift-saas"
    env_file:
      - ./.env.local
    ports:
      - "5432:5432"